name: Sonar Code Coverage
on:
  # trigger manually. Can be used to validate feature branches before open pull request
  workflow_dispatch:
    inputs:
      codecoveragetool:
        type: choice
        description: Code Coverage Tool
        required: true
        default: dotnet-coverage
        options:
          - dotnet-coverage
  push: 
    branches:
      - main
      
jobs:
  Application-Build-Test:
    runs-on: windows-latest
    
    steps:     
      - name: long path
        shell: pwsh
        run: |
          git config --system core.longpaths true

      - name: Checkout code
        uses: actions/checkout@v3
                    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup VSTest
        # id: setup_vstest
        uses: darenm/Setup-VSTest@v1

      - name: Restore packages
        run: |
          nuget restore WebAppFramework.sln

      - name: Build with Release
        run: |
          msbuild /p:Configuration=Release WebAppFramework.sln
      
      - name: Run Tests
        # id: run_vstest
        working-directory: WebAppFramework.Unit.Tests\bin\Release
        run: |
          vstest.console.exe .\WebAppFramework.Unit.Tests.dll 
        # /EnableCodeCoverage /Logger:trx;LogFileName=SonarqubeCoverage.trx

      - name: Download Sonar-Scanner
        working-directory: ./
        run: |
          Invoke-WebRequest -Uri https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.15.0.80890/sonar-scanner-msbuild-5.15.0.80890-net46.zip -OutFile ".\sonar-scanner\sonar-scanner-msbuild.zip"

      - name: Unzipp Sonar-Scanner
        run: |
          Expand-Archive -Force .\sonar-scanner\sonar-scanner-msbuild.zip .\Sonar-Scanner\unzipped
